#!/bin/bash

: '
Program: clssh
Purpose: To empty known_hosts file for the current user
Developer: CyberPanther232
'

rm -rf ~/.ssh/known_hosts ~/.ssh/known_hosts.old
echo "Known_hosts file deleted!"

